---
- name: "creates directory"
  file:
    path: ~/web
    state: directory

- name: "extract backend tar file"
  unarchive:
    src: artifact.tar.gz
    dest: ~/web

- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"
    
- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
    
- name: "start pm2"
    shell: |
        npm install
        pm2 stop default
        pm2 start npm -- start