version: 2.1

commands:
  revert-migrations1:
    description: Revert the last migration if successfully run in the current workflow.
    parameters:
      # Add parameter here     
    steps:
      - attach_workspace:
          at: $(pwd)
      - run:
          name: Revert migrations
          command: |
            echo "------------"
            pwd
            echo "------------"
            echo $(ls ~/)
            echo "------------"
            cat migrations_dump.txt
jobs:
  test:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - revert-migrations1
      
      
  test2:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Run migrations
          command: |
            mkdir ~/project/backend/
            cd ~/project/backend
            echo "------------"
            echo 'text here' > migrations_dump.txt
            echo "------------"
      - persist_to_workspace:
          root: ~/project/backend
          paths:
            - migrations_dump.txt
      
workflows:
  default:
    jobs:
      - test2
      - test:
          requires: [test2]